sudo: required

services:
  - docker

language: java

jdk:
 - oraclejdk8

os:
  - linux

cache:
  directories:
  - $HOME/.gradle
  		  
script:
 - ./gradlew check
 - docker-compose up --build -d
 - ./test.sh

after_script:
 - docker-compose down

after_success:
 - bash <(curl -s https://codecov.io/bash)
