sudo: required

services:
  - docker

language: java

jdk:
 - oraclejdk8

os:
  - linux

cache:
  directories:
  - $HOME/.gradle

before_script: 
 - docker-compose up --build -d
  		  
script:
 - .test.sh

after_script:
 - docker-compose down
