version: '3'
services:
  db:
    container_name: event-store-postgres-db
    networks: 
      - host
    image: postgres:9.4
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8081:5432
    volumes:
      - /data/event_store_db:/var/lib/postgresql/data

  event-store:
    build: .
    networks: 
      - host
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ADDR=${POSTGRES_ADDR}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 8080:8080

networks:
  host: 
