version: '2'
services:
  db:
    container_name: event-store-postgres-db
    image: postgres:9.4
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - /data/event_store_db:/var/lib/postgresql/data

  event-store:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT_ADDR=${POSTGRES_PORT_ADDR}
      - POSTGRES_PORT_PORT=${POSTGRES_PORT_PORT}
    ports:
      - 8080:8080
