version: '2'
services:
  db:
    container_name: event-store-postgres-db
    image: postgres:9.4
    environment:
      - POSTGRES_DB=event-store
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    ports:
      - 5432:5432
    volumes:
      - /data/event_store_db:/var/lib/postgresql/data

  event-store:
    container_name: event-store
    build: build/docker
    depends_on:
      - db
    environment:
      - POSTGRES_DB=event-store
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_PORT_ADDR=localhost
      - POSTGRES_PORT_PORT=5432
    ports:
      - 8048:8048