spring:
  application:
    name: event-store
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://db:5432/event-store
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate