spring:
  profiles:
    active: prod
  application:
    name: event-store
  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDR}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    enabled: false
